//product
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const UPDATE_CART_ITEM_QUANTITY = "UPDATE_CART_ITEM_QUANTITY";

//service
export const ADD_SERVICE_TO_CART = "ADD_SERVICE_TO_CART";
export const REMOVE_SERVICE_FROM_CART = "REMOVE_SERVICE_FROM_CART";
export const CLEAR_SERVICE_CART = "CLEAR_SERVICE_CART";
// export const UPDAT_SERVICEE_CART_ITEM_QUANTITY = "UPDATE_SERVICE_CART_ITEM_QUANTITY";

export const FETCH_UNREAD_COUNT_REQUEST = 'FETCH_UNREAD_COUNT_REQUEST';
export const FETCH_UNREAD_COUNT_SUCCESS = 'FETCH_UNREAD_COUNT_SUCCESS';
export const FETCH_UNREAD_COUNT_FAILURE = 'FETCH_UNREAD_COUNT_FAILURE';
